# Generated by Django 4.2.7 on 2023-11-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Note',
        ),
    ]
