# Generated by Django 4.2.7 on 2023-11-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_options_remove_note_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.topic'),
        ),
    ]
